(SELECT * FROM (
            SELECT PST.PST_ENTR_ID PST_ENTR_ID,
            PST.AR_NBR FORACID,
            NVL(CP.NHOM_PHI, CP1.NHOM_PHI) FEE_GRP,
            NVL(CP.LOAI_PHI_CHI, CP1.LOAI_PHI_CHI) FEE_TP,
            NVL(CP.LOAI_SAN_PHAM, CP1.LOAI_SAN_PHAM) PRD_TP,
            'UT1' SRC_STM_CODE,
            AWM.FUNCTION_HASH02('NHOM_PHI_CHI',NVL(CP.NHOM_PHI, CP1.NHOM_PHI)) FEE_GRP_CODE ,
            AWM.FUNCTION_HASH02('LOAI_PHI_CHI',NVL(CP.LOAI_PHI_CHI, CP1.LOAI_PHI_CHI)) FEE_TP_CODE ,
            RANK() OVER(PARTITION BY PST.PST_ENTR_ID ORDER BY CP.TT_UU_TIEN, CP1.TT_UU_TIEN ASC) RNK
FROM AWM.TWT_PST_ENTR_FEE PST
LEFT JOIN AWM.TBL_XLS_MAP_THE_PL_PHI_CHI CP ON PST.AR_NBR = CP.DIEU_KIEN_TAI_KHOAN
    AND CP.LOAI_LOGIC = 'UU_TIEN_01' AND SUBSTR(PST.AR_NBR,1,4) = 1000
    AND NVL(PST.DSC || PST.DSC2,' ') LIKE '%' || CP.DIEU_KIEN_REMARK1 || '%'
    AND NVL(PST.ADT_DLT_INFO,' ') LIKE '%' || CP.DIEU_KIEN_REMARK2 || '%'
LEFT JOIN AWM.TBL_XLS_MAP_THE_PL_PHI_CHI CP1 ON PST.AR_NBR LIKE '%' || REPLACE(CP1.DIEU_KIEN_TAI_KHOAN, 'SOL','')
    AND CP1.LOAI_LOGIC = 'UU_TIEN_01' AND SUBSTR(PST.AR_NBR,1,4) <> 1000
    AND NVL(PST.DSC || PST.DSC2,' ') LIKE '%' || CP1.DIEU_KIEN_REMARK1 || '%'
    AND NVL(PST.ADT_DLT_INFO,' ') LIKE '%' || CP1.DIEU_KIEN_REMARK2 || '%'
) WHERE RNK = 1 AND FEE_GRP_CODE IS NOT NULL) OUTPUTSIGNATURE_02130801_RMAPP
---------------------------------------------------------------------------------------
(
SELECT * FROM (
            SELECT PST.PST_ENTR_ID PST_ENTR_ID,
            PST.AR_NBR FORACID,
            NVL(CP.NHOM_PHI, CP1.NHOM_PHI) FEE_GRP,
            NVL(CP.LOAI_PHI_CHI, CP1.LOAI_PHI_CHI) FEE_TP,
        CASE
            WHEN   PST.DSC || PST.DSC2 LIKE '%HUY HOAN TIEN BS%' THEN TRIM(SUBSTR(PST.DSC || PST.DSC2,INSTR(PST.DSC || PST.DSC2,'HUY HOAN TIEN BS')+20,(INSTR(PST.DSC || PST.DSC2,',',1,1)-(INSTR(PST.DSC || PST.DSC2,'HUY HOAN TIEN BS')+20+7)) ))
            WHEN   PST.DSC || PST.DSC2 LIKE '%HOAN TIEN BS%' THEN TRIM(SUBSTR(PST.DSC || PST.DSC2,INSTR(PST.DSC || PST.DSC2,'HOAN TIEN BS')+16,(INSTR(PST.DSC || PST.DSC2,',',1,1)-(INSTR(PST.DSC || PST.DSC2,'HOAN TIEN BS')+16+7)) ))        
            WHEN   PST.DSC || PST.DSC2 LIKE '%HUY HOAN TIEN CHO%' THEN TRIM(SUBSTR(PST.DSC || PST.DSC2,INSTR(PST.DSC || PST.DSC2,'HUY HOAN TIEN CHO')+21,(INSTR(PST.DSC || PST.DSC2,',',1,1)-(INSTR(PST.DSC || PST.DSC2,'HUY HOAN TIEN CHO')+21+7)) ))
            WHEN   PST.DSC || PST.DSC2 LIKE '%HOAN TIEN THE%' THEN TRIM(SUBSTR(PST.DSC || PST.DSC2,INSTR(PST.DSC || PST.DSC2,'HOAN TIEN THE')+13,(INSTR(PST.DSC || PST.DSC2,',',1,1)-(INSTR(PST.DSC || PST.DSC2,'HOAN TIEN THE')+13+7)) ))
            ELSE NVL(TRIM(SUBSTR(PST.DSC || PST.DSC2,INSTR(PST.DSC || PST.DSC2,'HOAN TIEN')+9,(INSTR(PST.DSC || PST.DSC2,',',1,1)-(INSTR(PST.DSC || PST.DSC2,'HOAN TIEN')+9)) )),
                    TRIM(SUBSTR(PST.DSC || PST.DSC2,INSTR(PST.DSC || PST.DSC2,'THE')+3,LENGTH(PST.DSC || PST.DSC2)))  )
                    END PRD_TP,
                    'UT2' SRC_STM_CODE,
                    AWM.FUNCTION_HASH02('NHOM_PHI_CHI',NVL(CP.NHOM_PHI, CP1.NHOM_PHI)) FEE_GRP_CODE ,
                    AWM.FUNCTION_HASH02('LOAI_PHI_CHI',NVL(CP.LOAI_PHI_CHI, CP1.LOAI_PHI_CHI)) FEE_TP_CODE ,
                    RANK() OVER(PARTITION BY PST.PST_ENTR_ID ORDER BY CP.TT_UU_TIEN, CP1.TT_UU_TIEN ASC) RNK
FROM AWM.TWT_PST_ENTR_FEE PST
LEFT JOIN AWM.TBL_XLS_MAP_THE_PL_PHI_CHI CP ON PST.AR_NBR = CP.DIEU_KIEN_TAI_KHOAN
    AND CP.LOAI_LOGIC = 'UU_TIEN_01_HOAN_TIEN' AND SUBSTR(PST.AR_NBR,1,4) = 1000
    AND NVL(PST.DSC || PST.DSC2,' ') LIKE '%' || CP.DIEU_KIEN_REMARK1 || '%'
    AND NVL(PST.ADT_DLT_INFO,' ') LIKE '%' || CP.DIEU_KIEN_REMARK2 || '%'
LEFT JOIN AWM.TBL_XLS_MAP_THE_PL_PHI_CHI CP1 ON PST.AR_NBR LIKE '%' || REPLACE(CP1.DIEU_KIEN_TAI_KHOAN, 'SOL','')
    AND CP1.LOAI_LOGIC = 'UU_TIEN_01_HOAN_TIEN' AND SUBSTR(PST.AR_NBR,1,4) <> 1000
    AND NVL(PST.DSC || PST.DSC2,' ') LIKE '%' || CP1.DIEU_KIEN_REMARK1 || '%'
    AND NVL(PST.ADT_DLT_INFO,' ') LIKE '%' || CP1.DIEU_KIEN_REMARK2|| '%'
WHERE 1=1 AND NOT EXISTS(
    SELECT 1 FROM  AWM.TWT_EXPN_TP
    WHERE PST.PST_ENTR_ID = TWT_EXPN_TP.PST_ENTR_ID
    AND TWT_EXPN_TP.SRC_STM_CODE = 'UT1')
) WHERE RNK = 1 AND FEE_GRP_CODE IS NOT NULL
) OUTPUTSIGNATURE_02130801_RMAPP
--------------------------------------------------------------------------------------------------
(SELECT * FROM (
SELECT PST.PST_ENTR_ID PST_ENTR_ID,
PST.AR_NBR FORACID,
NVL(CP.NHOM_PHI, CP1.NHOM_PHI) FEE_GRP,
NVL(CP.LOAI_PHI_CHI, CP1.LOAI_PHI_CHI) FEE_TP,
NVL(CP.LOAI_SAN_PHAM, CP1.LOAI_SAN_PHAM) PRD_TP,
'UT3' SRC_STM_CODE,
AWM.FUNCTION_HASH02('NHOM_PHI_CHI',NVL(CP.NHOM_PHI, CP1.NHOM_PHI)) FEE_GRP_CODE ,
AWM.FUNCTION_HASH02('LOAI_PHI_CHI',NVL(CP.LOAI_PHI_CHI, CP1.LOAI_PHI_CHI)) FEE_TP_CODE ,
RANK() OVER(PARTITION BY PST.PST_ENTR_ID ORDER BY CP.TT_UU_TIEN, CP1.TT_UU_TIEN ASC) RNK
FROM AWM.TWT_PST_ENTR_FEE PST
LEFT JOIN AWM.TBL_XLS_MAP_THE_PL_PHI_CHI CP ON PST.AR_NBR = CP.DIEU_KIEN_TAI_KHOAN
AND CP.LOAI_LOGIC = 'UU_TIEN_02' AND SUBSTR(PST.AR_NBR,1,4) = 1000
LEFT JOIN AWM.TBL_XLS_MAP_THE_PL_PHI_CHI CP1 ON PST.AR_NBR LIKE '%' || REPLACE(CP1.DIEU_KIEN_TAI_KHOAN, 'SOL','')
AND CP1.LOAI_LOGIC = 'UU_TIEN_02' AND SUBSTR(PST.AR_NBR,1,4) <> 1000
WHERE 1 = 1
AND NOT EXISTS(
    SELECT 1 FROM  AWM.TWT_EXPN_TP
    WHERE PST.PST_ENTR_ID = TWT_EXPN_TP.PST_ENTR_ID
    AND TWT_EXPN_TP.SRC_STM_CODE IN ('UT1','UT2'))
) WHERE RNK = 1 AND FEE_GRP_CODE IS NOT NULL
) OUTPUTSIGNATURE_02130801_RMAPP
-------------------------------------------------------------------------------------------------------
(SELECT * FROM (
SELECT PST.PST_ENTR_ID PST_ENTR_ID,
PST.AR_NBR FORACID,
NVL(CP.NHOM_PHI, CP1.NHOM_PHI) FEE_GRP,
NVL(CP.LOAI_PHI_CHI, CP1.LOAI_PHI_CHI) FEE_TP,
NVL(CP.LOAI_SAN_PHAM, CP1.LOAI_SAN_PHAM) PRD_TP,
'UT4' SRC_STM_CODE,
AWM.FUNCTION_HASH02('NHOM_PHI_CHI',NVL(CP.NHOM_PHI, CP1.NHOM_PHI)) FEE_GRP_CODE ,
AWM.FUNCTION_HASH02('LOAI_PHI_CHI',NVL(CP.LOAI_PHI_CHI, CP1.LOAI_PHI_CHI)) FEE_TP_CODE ,
RANK() OVER(PARTITION BY PST.PST_ENTR_ID ORDER BY CP.TT_UU_TIEN, CP1.TT_UU_TIEN ASC) RNK
FROM AWM.TWT_PST_ENTR_FEE PST
LEFT JOIN AWM.TBL_XLS_MAP_THE_PL_PHI_CHI CP ON PST.AR_NBR LIKE '%' ||CP.DIEU_KIEN_TAI_KHOAN || '___'
AND CP.LOAI_LOGIC = 'UU_TIEN_03' AND SUBSTR(PST.AR_NBR,1,4) = 1000
LEFT JOIN AWM.TBL_XLS_MAP_THE_PL_PHI_CHI CP1 ON PST.AR_NBR LIKE '%' || REPLACE(CP.DIEU_KIEN_TAI_KHOAN, 'SOL','') || '___'
AND CP1.LOAI_LOGIC = 'UU_TIEN_03' AND SUBSTR(PST.AR_NBR,1,4) <> 1000
WHERE 1 = 1
AND NOT EXISTS(
    SELECT 1 FROM  AWM.TWT_EXPN_TP
    WHERE PST.PST_ENTR_ID = TWT_EXPN_TP.PST_ENTR_ID
    AND TWT_EXPN_TP.SRC_STM_CODE IN ('UT1','UT2','UT3'))
) WHERE RNK = 1 AND FEE_GRP_CODE IS NOT NULL ) OUTPUTSIGNATURE_02130801_RMAPP